#!/bin/bash
# Here put anything that is needed to start the service.
# Note that currently this is run directly after install
# i.e. 'service apache2 start'
if [ -f /etc/init.d/promise ]; then
    /etc/init.d/promise restart
fi
